format_version: v1.0
configName: lcdc_rgba888_mxt_9x60_wvga
folderName: evcharger_9x60_cu_tm5000
frameworkPath: C:\Users\c40450\harmony3_evcharger
processor: SAM9X60D1G
projectName: evcharger_9x60_cu_tm5000
settings:
  PackageFilter: ''
  FORCE_OPTIMIZATION: 'false'
  GENERATE_BACKUP: 'true'
  TRUSTZONE: 'false'
  CMSISPath: dev_packs\arm\CMSIS\5.8.0
  MERGE_STRATEGY: USER_ALL
  DFPPath: dev_packs\Microchip\SAM9X60_DFP\1.7.85\atdf\SAM9X60D1G.atdf
